config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  root 'home#index'
  resources :friends
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block"  %>
    <%= form.text_field :last_name , class:"form-control"  %>
  </div>

  <div class:"form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email , class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone , class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :twitter, style: "display: block"%>
    <%= form.text_field :twitter , class:"form-control"  %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:'btn btn-outline-secondary' %>
  </div>
  <br>
  <div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-outline-secondary" %>
  </div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
    <tr>
    <td><%= friend.id %></td>
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twitter %></td>
    <td><%= link_to "Show", friend, class:"btn btn-secondary" %></td>
    <td><%= link_to "Edit", edit_friend_path(friend), class:"btn btn-secondary" %></td>
    <td><%= button_to "Delete", friend, method: :delete, class:"btn btn-secondary" %></td>
    </tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
   <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Id</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        
      </tr>
    </thead>
    <tbody>
  <% @friends.each do |friend| %>
    <%= render friend %>
    
  <% end %>
  </tbody>
  </table>
</div>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>New friend</h1>
<%= render "form", friend: @friend %>
<br>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="card" style="width: 18rem;">
  <div class="card-header">
    <%=@friend.first_name + ' ' + @friend.last_name%>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @friend.email %></li>
    <li class="list-group-item"><%= @friend.phone %></li>
    <li class="list-group-item"><%= @friend.twitter %></li>
    
  </ul>
</div>


<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary mt-1" %>
  <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-secondary mt-1"%>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary mt-1" %>
  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Friends', friends_path , class:"nav-link" %>
        </li>
      </ul>
      <span class="navbar-text">
        Rails === DJANGO
      </span>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<p>About Page </p>

app/views/home/index.html.erb
<p>Hellowwwwwwwwwwww</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Friends-list!!</title>
  </head>
  <body>
  <div class="container">
    <%= render 'home/header' %>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <%end%>
    <%= yield %>
  </div>
  </body>
</html>